[package]
name = "translate"
version = "0.1.0"
authors = ["P.J. Finlay"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.4.0"
